apiVersion: guestops.io/v1alpha1
kind: AdminCredentialRotationPolicy
metadata:
  name: linux-password-external
  namespace: test-vms 
spec:
  targets:
    selector:
      matchLabels:
        rotation: linux-external
  os: linux
  method:
    type: ssh
    user: root
    port: 22
    auth:
      bootstrapSecretRef: linux-pass
  rotation:
    kind: linux-password
    source: external
    externalSecretRef: vault-linux-password-secret
  schedule: "0 */12 * * *"
  trigger:
    enableAnnotation: true
