apiVersion: guestops.io/v1alpha1
kind: AdminCredentialRotationPolicy
metadata:
  name: linux-password-gen
  namespace: virt-ops
spec:
  targets:
    selector:
      matchLabels:
        role: linux-admin
  os: linux
  method:
    type: ssh
    user: usertest
    port: 22
    auth:
      bootstrapSecretRef: bootstrap-ssh-password
  rotation:
    kind: linux-password
    source: generate
    passwordPolicy:
      length: 24
      minUpper: 1
      minLower: 1
      minDigits: 1
      minSpecial: 1
  schedule: "0 */12 * * *"
  concurrency:
    maxConcurrent: 3
  trigger:
    enableAnnotation: true
