apiVersion: guestops.io/v1alpha1
kind: AdminCredentialRotationPolicy
metadata:
  name: windows-password-external
  namespace: test-vms
spec:
  targets:
    selector:
      matchLabels:
        rotation: windows-external
  os: windows
  method:
    type: winrm
    user: Administrator
    port: 5985
    tls: false 
    auth:
      bootstrapSecretRef: bootstrap-win
  rotation:
    kind: windows-password
    source: external
    externalSecretRef: vault-windows-password-secret
  schedule: "0 */12 * * *"
  trigger:
    enableAnnotation: true
