apiVersion: guestops.io/v1alpha1
kind: AdminCredentialRotationPolicy
metadata:
  name: win-admin-gen
  namespace: virt-ops
spec:
  targets:
    selector:
      matchLabels:
        role: windows-admin
  os: windows
  method:
    type: winrm
    user: Administrator
    port: 5985
    tls: false
    auth:
      bootstrapSecretRef: bootstrap-win
  rotation:
    kind: windows-password
    source: generate
    length: 24
  schedule: "0 3 * * *"
  concurrency:
    maxConcurrent: 1
  trigger:
    enableAnnotation: true
