apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtops-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtops-operator-role
subjects:
  - kind: ServiceAccount
    name: virtops-operator
    namespace: virt-ops
